title: Yuqiao (Echo) Zhong # your name (or website title) here
logo: "IMG_7644.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently pursuing Master of Business Analytics degree from Simon Business School, University of Rochester 
  <br><br>
  <a href="https://www.linkedin.com/in/yuqiaoechozhong/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.youtube.com/channel/UC5PP8jKIxv6yoyoTHau6Z0w?view_as=subscriber">View My YouTube Channel</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
